### ISSUE TITLE
No module named "pnames"

### ISSUE THREAD

**Issue by quarkquartet** [hbprosper/hepmc2root#3]
I run this package to convert an hepmc to root. But I got this error:
```
Traceback (most recent call last):
  File "/Users/quarkquartet/Work/hepmc2root/bin/hepmc2root.py", line 42, in <module>
    from pnames import particleName
  File "/Users/quarkquartet/Work/root/lib/ROOT/_facade.py", line 153, in _importhook
    return _orig_ihook(name, *args, **kwds)
ModuleNotFoundError: No module named 'pnames'
```
Is this a problem from the new ROOT version?

**Comment by quarkquartet** [comment]
OK that's a problem from not running `setup.sh`. This shell script should be run before doing anything.
